Update 2bfuzz.py
I am patching the Broken Pipe bug. Below is an example of Traceback, which no longer happens.
Traceback (most recent call last):
  File "/usr/local/bin/2bfuzz", line 162, in <module>
    main()
  File "/usr/local/bin/2bfuzz", line 144, in main
    radamsa_fuzzer(ip,port,pattern_file,args.sleep)
  File "/usr/local/bin/2bfuzz", line 114, in radamsa_fuzzer
    last_payload = tcp_fuzzer(ip,port,payload,last_payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/2bfuzz", line 81, in tcp_fuzzer
    send_bytes(sock,payload)
  File "/usr/local/bin/2bfuzz", line 73, in send_bytes
    sock.sendall(payload)
BrokenPipeError: [Errno 32] Broken pipe